### ISSUE TITLE
 INFOGRAFIA 

### ISSUE THREAD

**Issue by Valentiin01** [SistemasTecTlaxiaco/infografia-de-las-librerias-Valentiin01#2]
[Genaro Santiago Valentin_INFOGRAFÍA.pdf](https://github.com/SistemasTecTlaxiaco/infografia-de-las-librerias-Valentiin01/files/6355315/Genaro.Santiago.Valentin_INFOGRAFIA.pdf)

**Comment by CxrlosMX** [comment]
Excelente trabajo compañero, buen diseño y buen uso de los colores.
Porcentaje obtenido: 20%

**Comment by josealfredo79** [comment]
Como se entrego al final del semestre...la calificacion no puede ser igual a los que entregaron en tiempo
